### ISSUE TITLE
RGB and RGBA colors is not highlited.

### ISSUE THREAD

**Issue by Deadricss5** [khrystalz/khrystalz-ui#3]
When using this theme+Color Highlighter, RGB and RGBA color is not highlighted.
![screenshot](https://cloud.githubusercontent.com/assets/20385019/21954823/52959c6c-da65-11e6-8158-a99f3d4f6073.png)

**Comment by unzico** [comment]
Hi, sorry for my late response.
I've looked into it and it seems to be a general problem, when using a custom theme with 'Color Highlighter'.
My research indicates, it's due to the `addModeClass: true` attribute in the package.json file (ref: [Creating Themes in Brackets](https://github.com/adobe/brackets/wiki/Creating-Themes#packagejson)), which seems to interfere with the addon's way of detecting the specific html element.
